const peopleText = [
  {
    people_id: 'rpp:01',
    name: 'Abel Kirui',
    nationality: 'Kenya',
    born_date: '6 April 1982',
  },
  {
    people_id: 'rpp:02',
    name: 'Abel Shavil',
    nationality: 'Portugal',
    born_date: '30 November 1972',
  },
  {
    people_id: 'rpp:03',
    name: 'Abu Diaby',
    nationality: 'French',
    born_date: '11 May 1986',
  },
  {
    people_id: 'rpp:04',
    name: 'Adil Lamy',
    nationality: 'French',
    born_date: '27 December 1985',
  },
  {
    people_id: 'rpp:05',
    name: 'Adolf Hitler',
    nationality: 'German',
    born_date: '20 April 1889',
  },
  {
    people_id: 'rpp:06',
    name: 'Albert II',
    nationality: 'Belgian',
    born_date: '6 June 1934',
  },
  {
    people_id: 'rpp:07',
    name: 'Alberto Ascari',
    nationality: 'Italian',
    born_date: '13 July 1918',
  },
  {
    people_id: 'rpp:08',
    name: 'Amelia Earhart',
    nationality: 'American',
    born_date: 'July 24, 1897',
  },
  {
    people_id: 'rpp:09',
    name: 'Arab Philip',
    nationality: 'Roman',
    born_date: 'c. 204',
  },
  {
    people_id: 'rpp:10',
    name: 'Arno Danielle',
    nationality: 'Occitan',
    born_date: '1180',
  },
  {
    people_id: 'rpp:11',
    name: 'Arnold Schwarzenegger',
    nationality: 'American',
    born_date: 'July 30, 1947',
  },
  {
    people_id: 'rpp:12',
    name: 'Attil Rambo',
    nationality: 'French',
    born_date: '20 October 1854',
  },
  {
    people_id: 'rpp:13',
    name: 'Bob Dylan',
    nationality: 'American',
    born_date: 'May 24, 1941',
  },
  {
    people_id: 'rpp:14',
    name: 'Chen Ding',
    nationality: 'Chinese',
    born_date: 'August 5, 1992',
  },
  {
    people_id: 'rpp:15',
    name: 'Deborah Conpanioni',
    nationality: 'Italian',
    born_date: 'June 4, 1970',
  },
  {
    people_id: 'rpp:16',
    name: 'Horst Keller',
    nationality: 'German',
    born_date: '22 February 1943',
  },
  {
    people_id: 'rpp:17',
    name: 'Huang Xianwei',
    nationality: 'Chinese',
    born_date: '13 November 1899',
  },
  {
    people_id: 'rpp:18',
    name: 'Hugo Lloris',
    nationality: 'French',
    born_date: '26 December 1986',
  },
  {
    people_id: 'rpp:19',
    name: 'Jacques Brill',
    nationality: 'Belgian',
    born_date: '8 April 1929',
  },
  {
    people_id: 'rpp:20',
    name: 'Jacques Chirac',
    nationality: 'French',
    born_date: '29 November 1932',
  },
  {
    people_id: 'rpp:21',
    name: 'Madonna',
    nationality: 'American',
    born_date: 'August 16, 1958',
  },
  {
    people_id: 'rpp:22',
    name: 'Makrinus',
    nationality: 'Roman',
    born_date: 'c. 165',
  },
  {
    people_id: 'rpp:23',
    name: 'Mara',
    nationality: 'French',
    born_date: '18 March 1842',
  },
  {
    people_id: 'rpp:24',
    name: 'Marc Miller',
    nationality: 'English',
    born_date: '24 December 1969',
  },
  {
    people_id: 'rpp:25',
    name: 'Marcel Dorette',
    nationality: 'French',
    born_date: '3 May 1896',
  },
  {
    people_id: 'rpp:26',
    name: 'Marcel Heshill',
    nationality: 'austrian',
    born_date: '2 March 1989',
  },
  {
    people_id: 'rpp:27',
    name: 'Marcus Aurelius',
    nationality: 'Roman',
    born_date: '26 April 121',
  },
  {
    people_id: 'rpp:28',
    name: 'Mark Girardley',
    nationality: 'Australian',
    born_date: '29 September 1961',
  },
  {
    people_id: 'rpp:29',
    name: 'Mark Hopps',
    nationality: 'American',
    born_date: 'May 3, 1932',
  },
  {
    people_id: 'rpp:30',
    name: 'Marvin Martin',
    nationality: 'French',
    born_date: '10 January 1988',
  },
  {
    people_id: 'rpp:31',
    name: 'Matial',
    nationality: 'Roman',
    born_date: 'March, between 38 and 41 AD',
  },
  {
    people_id: 'rpp:32',
    name: 'Matthew Debich',
    nationality: 'French',
    born_date: '28 July 1985',
  },
  {
    people_id: 'rpp:33',
    name: 'Matthew Knell',
    nationality: 'English',
    born_date: '9 May 1950',
  },
  {
    people_id: 'rpp:34',
    name: 'Matthew Vaughan',
    nationality: 'English',
    born_date: '7 March 1971',
  },
  {
    people_id: 'rpp:35',
    name: 'Matthew Warbane',
    nationality: 'French',
    born_date: '28 September 1984',
  },
  {
    people_id: 'rpp:36',
    name: 'Maximius Rex',
    nationality: 'Roman',
    born_date: 'c. 173',
  },
  {
    people_id: 'rpp:37',
    name: 'McWillimberg',
    nationality: 'Scottish',
    born_date: '13 June 1831',
  },
  {
    people_id: 'rpp:38',
    name: 'Mike Orfield',
    nationality: 'English',
    born_date: '15 May 1953',
  },
  {
    people_id: 'rpp:39',
    name: 'Miley Hilla',
    nationality: 'American',
    born_date: 'November 23, 1992',
  },
  {
    people_id: 'rpp:40',
    name: 'Rachel Mado',
    nationality: 'Australian',
    born_date: '21 May 1930',
  },
  {
    people_id: 'rpp:41',
    name: 'Renault Lavigny',
    nationality: 'French',
    born_date: '18 September 1986',
  },
  {
    people_id: 'rpp:42',
    name: 'Rizal',
    nationality: 'Filipino',
    born_date: 'June 19, 1861',
  },
  {
    people_id: 'rpp:43',
    name: 'Rufus R. Jones',
    nationality: 'American',
    born_date: 'July 4, 1933',
  },
  {
    people_id: 'rpp:44',
    name: 'Ruhr Abiol',
    nationality: 'Spanish',
    born_date: '4 September 1985',
  },
  {
    people_id: 'rpp:45',
    name: 'Vesbah',
    nationality: 'Roman',
    born_date: '17 November 9 AD',
  },
  {
    people_id: 'rpp:46',
    name: 'Yaroslav Hasek',
    nationality: 'Czech',
    born_date: '30 April 1883',
  },
  {
    people_id: 'rpp:47',
    name: 'Yasin Benzia',
    nationality: 'Algerian',
    born_date: '8 September 1994',
  },
  {
    people_id: 'rpp:48',
    name: 'Zinedine Zidane',
    nationality: 'French',
    born_date: '23 June 1972',
  },
];

export default peopleText;
