const peopleDict = {"Abel Kirui":"rpp:01",
"Abel Shavil":"rpp:02",
"Abu Diaby":"rpp:03",
"Adil Lamy":"rpp:04",
"Adolf Hitler":"rpp:05",
"Albert II":"rpp:06",
"Alberto Ascari":"rpp:07",
"Amelia Earhart":"rpp:08",
"Arab Philip":"rpp:09",
"Arno Danielle":"rpp:10",
"Arnold Schwarzenegger":"rpp:11",
"Attil Rambo":"rpp:12",
"Bob Dylan":"rpp:13",
"Chen Ding":"rpp:14",
"Deborah Conpanioni":"rpp:15",
"Horst Keller":"rpp:16",
"Huang Xianwei":"rpp:17",
"Hugo Lloris":"rpp:18",
"Jacques Brill":"rpp:19",
"Jacques Chirac":"rpp:20",
"Madonna":"rpp:21",
"Makrinus":"rpp:22",
"Mara":"rpp:23",
"Marc Miller":"rpp:24",
"Marcel Dorette":"rpp:25",
"Marcel Heshill":"rpp:26",
"Marcus Aurelius":"rpp:27",
"Mark Girardley":"rpp:28",
"Mark Hopps":"rpp:29",
"Marvin Martin":"rpp:30",
"Matial":"rpp:31",
"Matthew Debich":"rpp:32",
"Matthew Knell":"rpp:33",
"Matthew Vaughan":"rpp:34",
"Matthew Warbane":"rpp:35",
"Maximius Rex":"rpp:36",
"McWillimberg":"rpp:37",
"Mike Orfield":"rpp:38",
"Miley Hilla":"rpp:39",
"Rachel Mado":"rpp:40",
"Renault Lavigny":"rpp:41",
"Rizal":"rpp:42",
"Rufus R. Jones":"rpp:43",
"Ruhr Abiol":"rpp:44",
"Vesbah":"rpp:45",
"Yaroslav Hasek":"rpp:46",
"Yasin Benzia":"rpp:47",
"Zinedine Zidane":"rpp:48",
};

export default peopleDict;