const cityText = [
  {
    city_id: 'wd:Q64',
    name: 'Berlin',
    sovereign_state: 'Germany',
    total_area: '891.7',
    total_population: '3,748,148',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q70',
    name: 'Bern',
    sovereign_state: 'Switzerland',
    total_area: '51.62',
    total_population: '133,791',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q84',
    name: 'London',
    sovereign_state: 'United Kingdom',
    total_area: '1,572',
    total_population: '9,126,366',
    time_zone: 'UTC',
  },
  {
    city_id: 'wd:Q85',
    name: 'Cairo',
    sovereign_state: 'Egypt',
    total_area: '606',
    total_population: '19,500,000',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q90',
    name: 'Paris',
    sovereign_state: 'France',
    total_area: '105.4',
    total_population: '2,140,526',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q174',
    name: 'Sao paulo',
    sovereign_state: 'Brazil',
    total_area: '1,521.11',
    total_population: '12,176,866',
    time_zone: 'UTC−3',
  },
  {
    city_id: 'wd:Q216',
    name: 'Vilnius',
    sovereign_state: 'Lithuania',
    total_area: '401',
    total_population: '536,631',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q220',
    name: 'Rome',
    sovereign_state: 'Italy',
    total_area: '1,285',
    total_population: '2,872,800',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q269',
    name: 'Tashkent',
    sovereign_state: 'Uzbekistan',
    total_area: '334.8',
    total_population: '2,485,900',
    time_zone: 'UTC+5',
  },
  {
    city_id: 'wd:Q270',
    name: 'Warsaw',
    sovereign_state: 'Poland',
    total_area: '517.24',
    total_population: '1,769,529',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q384',
    name: 'Skopje',
    sovereign_state: 'North Macedonia',
    total_area: '571.46',
    total_population: '544,086',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q437',
    name: 'Ljubljana',
    sovereign_state: 'Slovenia',
    total_area: '163.8',
    total_population: '290,010',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q472',
    name: 'Sofia',
    sovereign_state: 'Bulgaria',
    total_area: '492',
    total_population: '1,241,675',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q585',
    name: 'Oslo',
    sovereign_state: 'Norway',
    total_area: '480.76',
    total_population: '673,469',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q597',
    name: 'Lisbon',
    sovereign_state: 'Portugal',
    total_area: '100.05',
    total_population: '505,526',
    time_zone: 'UTC',
  },
  {
    city_id: 'wd:Q641',
    name: 'Venice',
    sovereign_state: 'Italy',
    total_area: '415.9',
    total_population: '261,321',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q649',
    name: 'Moscow',
    sovereign_state: 'Russia',
    total_area: '2,511',
    total_population: '12,506,468',
    time_zone: 'UTC+3',
  },
  {
    city_id: 'wd:Q727',
    name: 'Amsterdam',
    sovereign_state: 'Netherlands',
    total_area: '219.32',
    total_population: '854,047',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q807',
    name: 'Lausanne',
    sovereign_state: 'Switzerland',
    total_area: '41.37',
    total_population: '139,056',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q987',
    name: 'New Delhi',
    sovereign_state: 'India',
    total_area: '42.7',
    total_population: '257,803',
    time_zone: 'UTC+5:30',
  },
  {
    city_id: 'wd:Q994',
    name: 'Tbilisi',
    sovereign_state: 'Georgia',
    total_area: '504.2',
    total_population: '1,158,700',
    time_zone: 'UTC+4',
  },
  {
    city_id: 'wd:Q1085',
    name: 'Prague',
    sovereign_state: 'Czech Republic',
    total_area: '298',
    total_population: '1,301,132',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1218',
    name: 'Jerusalem',
    sovereign_state: 'Israel',
    total_area: '125.156',
    total_population: '901,302',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1335',
    name: 'Montevideo',
    sovereign_state: 'Uruguay',
    total_area: '201',
    total_population: '1,719,453',
    time_zone: 'UTC−3',
  },
  {
    city_id: 'wd:Q1362',
    name: 'Islamabad',
    sovereign_state: 'Pakistan',
    total_area: '906.5',
    total_population: '1,014,825',
    time_zone: 'UTC+5',
  },
  {
    city_id: 'wd:Q1435',
    name: 'Zagreb',
    sovereign_state: 'Croatia',
    total_area: '641',
    total_population: '802,588',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1486',
    name: 'Buenos Aires',
    sovereign_state: 'Argentina',
    total_area: '203',
    total_population: '2,891,082',
    time_zone: 'UTC−3',
  },
  {
    city_id: 'wd:Q1489',
    name: 'Mexico City',
    sovereign_state: 'Mexico',
    total_area: '1,485',
    total_population: '8,918,653',
    time_zone: 'UTC−6',
  },
  {
    city_id: 'wd:Q1491',
    name: 'La Paz',
    sovereign_state: 'Bolivia',
    total_area: '472',
    total_population: '757,184',
    time_zone: 'UTC−4',
  },
  {
    city_id: 'wd:Q1519',
    name: 'Abu Dhabi',
    sovereign_state: 'United Arab Emirates',
    total_area: '972',
    total_population: '1,205,963',
    time_zone: 'UTC+4',
  },
  {
    city_id: 'wd:Q1520',
    name: 'Astana',
    sovereign_state: 'Kazakhstan',
    total_area: '810.2',
    total_population: '1,029,556',
    time_zone: '	UTC+6',
  },
  {
    city_id: 'wd:Q1524',
    name: 'Athens',
    sovereign_state: 'Greece',
    total_area: '412',
    total_population: '3,090,508',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1530',
    name: 'Baghdad',
    sovereign_state: 'Iraq',
    total_area: '204.2',
    total_population: '8,765,000',
    time_zone: 'UTC+3',
  },
  {
    city_id: 'wd:Q1533',
    name: 'Caracas',
    sovereign_state: 'Venezuela',
    total_area: '433',
    total_population: '1,945,901',
    time_zone: 'UTC-4',
  },
  {
    city_id: 'wd:Q1563',
    name: 'Havana',
    sovereign_state: 'Cuba',
    total_area: '728.26',
    total_population: '2,106,146',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q1741',
    name: 'Vienna',
    sovereign_state: 'Austria',
    total_area: '414.8',
    total_population: '1,888,776',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1748',
    name: 'Copenhagen',
    sovereign_state: 'Denmark',
    total_area: '178.46',
    total_population: '1,627,705',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1754',
    name: 'Stockholm',
    sovereign_state: 'Sweden',
    total_area: '381.63',
    total_population: '1,562,136',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1757',
    name: 'Helsinki',
    sovereign_state: 'Finland',
    total_area: '715.48',
    total_population: '650,058',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1761',
    name: 'Dublin',
    sovereign_state: 'Ireland',
    total_area: '318',
    total_population: '1,173,179',
    time_zone: 'UTC',
  },
  {
    city_id: 'wd:Q1764',
    name: 'Reykjavik',
    sovereign_state: 'Iceland',
    total_area: '273',
    total_population: '128,793',
    time_zone: 'UTC',
  },
  {
    city_id: 'wd:Q1770',
    name: 'Tallinn',
    sovereign_state: 'Estonia',
    total_area: '159.2',
    total_population: '430,805',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1773',
    name: 'Riga',
    sovereign_state: 'Latvia',
    total_area: '324',
    total_population: '615,369',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1780',
    name: 'Bratislava',
    sovereign_state: 'Slovakia',
    total_area: '367.584',
    total_population: '432,508',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1781',
    name: 'Budapest',
    sovereign_state: 'Hungary',
    total_area: '525.2',
    total_population: '1,779,361',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1850',
    name: 'Phnom Penh',
    sovereign_state: 'Cambodia',
    total_area: '678.46',
    total_population: '1,501,725',
    time_zone: 'UTC+07:00',
  },
  {
    city_id: 'wd:Q1861',
    name: 'Bangkok',
    sovereign_state: 'Thailand',
    total_area: '1,568.737',
    total_population: '8,305,218',
    time_zone: 'UTC+07:00',
  },
  {
    city_id: 'wd:Q1863',
    name: 'Andorra la Vella',
    sovereign_state: 'Andorra',
    total_area: '12',
    total_population: '22,256',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1865',
    name: 'Kuala Lumpur',
    sovereign_state: 'Malaysia',
    total_area: '243',
    total_population: '1,790,000',
    time_zone: 'UTC+8',
  },
  {
    city_id: 'wd:Q1899',
    name: 'Kiev',
    sovereign_state: 'Ukraine',
    total_area: '839',
    total_population: '2,900,920',
    time_zone: 'UTC+2',
  },
  {
    city_id: 'wd:Q1930',
    name: 'Ottawa',
    sovereign_state: 'Canada',
    total_area: '2,778.13',
    total_population: '964,743',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q2044',
    name: 'Florence',
    sovereign_state: 'Italy',
    total_area: '102.32',
    total_population: '380,948',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q2280',
    name: 'Minsk',
    sovereign_state: 'Belarus',
    total_area: '409.5',
    total_population: '1,982,444',
    time_zone: 'UTC+3',
  },
  {
    city_id: 'wd:Q2467',
    name: 'Nassau',
    sovereign_state: 'Bahamas',
    total_area: '207',
    total_population: '274,400',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q2807',
    name: 'Madrid',
    sovereign_state: 'Spain',
    total_area: '604.3',
    total_population: '3,223,334',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q2841',
    name: 'Bogota',
    sovereign_state: 'Colombia',
    total_area: '1,587',
    total_population: '8,080,734',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q2844',
    name: 'Brasilia',
    sovereign_state: 'Brazil',
    total_area: '5,802',
    total_population: '3,039,444',
    time_zone: 'UTC−3',
  },
  {
    city_id: 'wd:Q2868',
    name: 'Lima',
    sovereign_state: 'Peru',
    total_area: '2,672.3',
    total_population: '8,852,000',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q3037',
    name: 'Kathmandu',
    sovereign_state: 'Nepal',
    total_area: '51',
    total_population: '975,453',
    time_zone: 'UTC+5:45',
  },
  {
    city_id: 'wd:Q3114',
    name: 'Canberra',
    sovereign_state: 'Australia',
    total_area: '814.2',
    total_population: '410,301',
    time_zone: 'UTC+10:00',
  },
  {
    city_id: 'wd:Q3130',
    name: 'Sydney',
    sovereign_state: 'Australia',
    total_area: '12,367.7',
    total_population: '5,230,330',
    time_zone: 'UTC+10',
  },
  {
    city_id: 'wd:Q3616',
    name: 'Tehran',
    sovereign_state: 'Iran',
    total_area: '574',
    total_population: '8,693,706',
    time_zone: 'UTC+03:30',
  },
  {
    city_id: 'wd:Q3630',
    name: 'Jakarta',
    sovereign_state: 'Indonesia',
    total_area: '661.5',
    total_population: '10,075,310',
    time_zone: 'UTC+7',
  },
  {
    city_id: 'wd:Q3640',
    name: 'Ankara',
    sovereign_state: 'Turkey',
    total_area: '24,521',
    total_population: '5,445,026',
    time_zone: 'UTC+3',
  },
  {
    city_id: 'wd:Q3711',
    name: 'Belgrade',
    sovereign_state: 'Serbia',
    total_area: '359.96',
    total_population: '1,166,763',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q8678',
    name: 'Rio de Janeiro',
    sovereign_state: 'Brazil',
    total_area: '1,221',
    total_population: '6,688,930',
    time_zone: 'UTC−3',
  },
  {
    city_id: 'wd:Q8684',
    name: 'Seoul',
    sovereign_state: 'South Korea',
    total_area: '605.21',
    total_population: '9,838,892',
    time_zone: 'UTC+9',
  },
  {
    city_id: 'wd:Q23661',
    name: 'Wellington',
    sovereign_state: 'New Zealand',
    total_area: '442',
    total_population: '418,500',
    time_zone: 'UTC+12',
  },
  {
    city_id: 'wd:Q1490',
    name: 'Tokyo',
    sovereign_state: 'Japan',
    total_area: '2,187.66',
    total_population: '13,839,910',
    time_zone: 'UTC+9',
  },
  {
    city_id: 'wd:Q406',
    name: 'Istanbul',
    sovereign_state: 'Turkey',
    total_area: '1,539',
    total_population: '15,067,724',
    time_zone: 'UTC+3',
  },
  {
    city_id: 'wd:Q956',
    name: 'Beijing',
    sovereign_state: "People's Republic of China",
    total_area: '16,410.5',
    total_population: '21,542,000',
    time_zone: 'UTC+8',
  },
  {
    city_id: 'wd:Q61',
    name: 'Washington',
    sovereign_state: 'United States',
    total_area: '177.0',
    total_population: '702,445',
    time_zone: 'UTC−5',
  },
  {
    city_id: 'wd:Q1842',
    name: 'Luxembourg City',
    sovereign_state: 'Luxembourg',
    total_area: '51.46',
    total_population: '116,323',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1555',
    name: 'Guatemala City',
    sovereign_state: 'Guatemala',
    total_area: '692',
    total_population: '1,026,749',
    time_zone: 'UTC-6',
  },
  {
    city_id: 'wd:Q1953',
    name: 'Yerevan',
    sovereign_state: 'Armenia',
    total_area: '223',
    total_population: '1,075,800',
    time_zone: 'UTC+4',
  },
  {
    city_id: 'wd:Q239',
    name: 'Brussels',
    sovereign_state: 'Belgium',
    total_area: '161.38',
    total_population: '1,191,604',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1858',
    name: 'Hanoi',
    sovereign_state: 'Vietnam',
    total_area: '319.56',
    total_population: '3,642,131',
    time_zone: 'UTC+07:00',
  },
  {
    city_id: 'wd:Q3572',
    name: 'Tunis',
    sovereign_state: 'Tunisia',
    total_area: '212.63',
    total_population: '638,845',
    time_zone: 'UTC+1',
  },
  {
    city_id: 'wd:Q1354',
    name: 'Dhaka',
    sovereign_state: 'Bangladesh',
    total_area: '306.38',
    total_population: '8,906,039',
    time_zone: 'UTC+6',
  },
  {
    city_id: 'wd:Q1461',
    name: 'Manila',
    sovereign_state: 'Philippines',
    total_area: '42.88',
    total_population: '1,780,148',
    time_zone: 'UTC+8',
  },
];

export default cityText;
